USE `U5G_ACS_FO`;

DELETE FROM `PROFILE_SET` WHERE `ID` in (42,43);

DELETE FROM `ISSUER_CONFIG` WHERE `ISSUER_NAME` in ('RCBC') and `ISSUER_CODE` = '00006';

DELETE FROM `CRYPTO_CONFIG` WHERE `ID` in (12,13);

DELETE FROM `BIN_RANGE` WHERE `PROFILE_SET_ID` in (42,43);