-- Generated by sql-script-generator
-- Version: 22R1-GE-3.5-SNAPSHOT
-- Date: Wed Sep 07 15:54:05 CEST 2022
-- Properties file: /json/ACS_RBA_TRIODOS_IAT.json
-- Template file: /templates/ACS_RBA_ROLLBACK_template.j2

USE `H0G_RBA`;

SET @service = 'ACS_U5G';
SET @issuer = '10000';

SELECT count(*) as countRulesetBeforeDelete FROM RULE_SET;
-- -----------------------------------------------------------------------------
-- DELETE of rulesets linked to :
-- service   : ACS_U5G
-- issuer    : 10000
-- subissuer : *
-- -----------------------------------------------------------------------------
SET @subIssuer = NULL;

SELECT ID FROM `ISSUER_CONFIG` WHERE `issuer` = @issuer AND `sub_issuer` is NULL ORDER BY id DESC LIMIT 1 INTO @issuerConfigId;

DELETE sp
FROM `SCORING_PROVIDER` sp
WHERE sp.issuer_config_id = @issuerConfigId;

DELETE ic
FROM `ISSUER_CONFIG` ic
WHERE ic.id = @issuerConfigId;
-- --------------------------------------------
-- DELETE ruleset 3DS2_NON-EEA
-- issuer    : 10000
-- subissuer : *
-- card_scheme : 
-- transaction_type : 
-- location : 
-- device_channel : 
-- --------------------------------------------
SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type is NULL AND card_scheme is NULL AND device_channel is NULL AND location is NULL ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

DELETE ov
FROM OPERAND_VALUE ov
WHERE ov.rule_set_id = @rule_set_id;

DELETE o
FROM OPERAND o
WHERE o.condition_id in (SELECT rc.id FROM RULE_CONDITION rc
                         JOIN RULE r on rc.rule_id=r.id
                         WHERE r.rule_set_id = @rule_set_id);

DELETE  rc
FROM RULE_CONDITION rc
WHERE rc.rule_id in (SELECT r.id FROM RULE r 
                     WHERE r.rule_set_id = @rule_set_id);

DELETE r
FROM RULE r
WHERE r.rule_set_id = @rule_set_id;

DELETE rs
FROM RULE_SET rs
WHERE rs.id = @rule_set_id;

-- --------------------------------------------
-- DELETE ruleset 3DS2_EEA
-- issuer    : 10000
-- subissuer : *
-- card_scheme : 
-- transaction_type : 
-- location : EEA
-- device_channel : 
-- --------------------------------------------
SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type is NULL AND card_scheme is NULL AND device_channel is NULL AND location = 'EEA' ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

DELETE ov
FROM OPERAND_VALUE ov
WHERE ov.rule_set_id = @rule_set_id;

DELETE o
FROM OPERAND o
WHERE o.condition_id in (SELECT rc.id FROM RULE_CONDITION rc
                         JOIN RULE r on rc.rule_id=r.id
                         WHERE r.rule_set_id = @rule_set_id);

DELETE  rc
FROM RULE_CONDITION rc
WHERE rc.rule_id in (SELECT r.id FROM RULE r 
                     WHERE r.rule_set_id = @rule_set_id);

DELETE r
FROM RULE r
WHERE r.rule_set_id = @rule_set_id;

DELETE rs
FROM RULE_SET rs
WHERE rs.id = @rule_set_id;

-- --------------------------------------------
-- DELETE ruleset 3RI_NON-EEA_VISA
-- issuer    : 10000
-- subissuer : *
-- card_scheme : VISA
-- transaction_type : PROT_2X_3DS
-- location : 
-- device_channel : 03
-- --------------------------------------------
SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'VISA' AND device_channel = '03' AND location is NULL ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

DELETE ov
FROM OPERAND_VALUE ov
WHERE ov.rule_set_id = @rule_set_id;

DELETE o
FROM OPERAND o
WHERE o.condition_id in (SELECT rc.id FROM RULE_CONDITION rc
                         JOIN RULE r on rc.rule_id=r.id
                         WHERE r.rule_set_id = @rule_set_id);

DELETE  rc
FROM RULE_CONDITION rc
WHERE rc.rule_id in (SELECT r.id FROM RULE r 
                     WHERE r.rule_set_id = @rule_set_id);

DELETE r
FROM RULE r
WHERE r.rule_set_id = @rule_set_id;

DELETE rs
FROM RULE_SET rs
WHERE rs.id = @rule_set_id;

-- --------------------------------------------
-- DELETE ruleset 3RI_NON-EEA_MASTERCARD
-- issuer    : 10000
-- subissuer : *
-- card_scheme : MASTERCARD
-- transaction_type : PROT_2X_3DS
-- location : 
-- device_channel : 03
-- --------------------------------------------
SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'MASTERCARD' AND device_channel = '03' AND location is NULL ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

DELETE ov
FROM OPERAND_VALUE ov
WHERE ov.rule_set_id = @rule_set_id;

DELETE o
FROM OPERAND o
WHERE o.condition_id in (SELECT rc.id FROM RULE_CONDITION rc
                         JOIN RULE r on rc.rule_id=r.id
                         WHERE r.rule_set_id = @rule_set_id);

DELETE  rc
FROM RULE_CONDITION rc
WHERE rc.rule_id in (SELECT r.id FROM RULE r 
                     WHERE r.rule_set_id = @rule_set_id);

DELETE r
FROM RULE r
WHERE r.rule_set_id = @rule_set_id;

DELETE rs
FROM RULE_SET rs
WHERE rs.id = @rule_set_id;

-- --------------------------------------------
-- DELETE ruleset 3RI_EEA_VISA
-- issuer    : 10000
-- subissuer : *
-- card_scheme : VISA
-- transaction_type : PROT_2X_3DS
-- location : EEA
-- device_channel : 03
-- --------------------------------------------
SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'VISA' AND device_channel = '03' AND location = 'EEA' ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

DELETE ov
FROM OPERAND_VALUE ov
WHERE ov.rule_set_id = @rule_set_id;

DELETE o
FROM OPERAND o
WHERE o.condition_id in (SELECT rc.id FROM RULE_CONDITION rc
                         JOIN RULE r on rc.rule_id=r.id
                         WHERE r.rule_set_id = @rule_set_id);

DELETE  rc
FROM RULE_CONDITION rc
WHERE rc.rule_id in (SELECT r.id FROM RULE r 
                     WHERE r.rule_set_id = @rule_set_id);

DELETE r
FROM RULE r
WHERE r.rule_set_id = @rule_set_id;

DELETE rs
FROM RULE_SET rs
WHERE rs.id = @rule_set_id;

-- --------------------------------------------
-- DELETE ruleset 3RI_EEA_MASTERCARD
-- issuer    : 10000
-- subissuer : *
-- card_scheme : MASTERCARD
-- transaction_type : PROT_2X_3DS
-- location : EEA
-- device_channel : 03
-- --------------------------------------------
SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'MASTERCARD' AND device_channel = '03' AND location = 'EEA' ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

DELETE ov
FROM OPERAND_VALUE ov
WHERE ov.rule_set_id = @rule_set_id;

DELETE o
FROM OPERAND o
WHERE o.condition_id in (SELECT rc.id FROM RULE_CONDITION rc
                         JOIN RULE r on rc.rule_id=r.id
                         WHERE r.rule_set_id = @rule_set_id);

DELETE  rc
FROM RULE_CONDITION rc
WHERE rc.rule_id in (SELECT r.id FROM RULE r 
                     WHERE r.rule_set_id = @rule_set_id);

DELETE r
FROM RULE r
WHERE r.rule_set_id = @rule_set_id;

DELETE rs
FROM RULE_SET rs
WHERE rs.id = @rule_set_id;



SELECT count(*) as countRulesetAfterDelete FROM RULE_SET;