-- Generated by sql-script-generator
-- Version: 22R1-GE-3.5-SNAPSHOT
-- Date: Wed Sep 07 15:47:57 CEST 2022
-- Properties file: /json/Configuration_IAT.json
-- Template file: /templates/ACS_ASR_ROLLBACK_template.j2

USE H0G_ASR;
-- ------------------------
-- ASR CONFIG FILE
-- service = ACS_U5G
-- issuer = 10000
-- subissuer = 
-- ------------------------
-- Beginning of data deletion --
SELECT "ACS_U5G-10000-%" INTO @service_code;

SELECT * FROM `CONFIGS` WHERE `CODE` like @service_code;
DELETE FROM `CONFIGS` WHERE `CODE` like @service_code;
SELECT * FROM `CONFIGS` WHERE `CODE` like @service_code;

SELECT * FROM `CONFIGS_SOURCES` WHERE `CODE` like @service_code;
DELETE FROM `CONFIGS_SOURCES` WHERE `CODE` like @service_code;
SELECT * FROM `CONFIGS_SOURCES` WHERE `CODE` like @service_code;

SELECT * FROM `CONFIGS_URLS` WHERE `CODE` like @service_code;
DELETE FROM `CONFIGS_URLS` WHERE `CODE` like @service_code;
SELECT * FROM `CONFIGS_URLS` WHERE `CODE` like @service_code;

-- End of data deletion
