-- Generated by sql-script-generator
-- Version: 22R1-GE-3.5-SNAPSHOT
-- Date: Wed Sep 07 15:53:30 CEST 2022
-- Properties file: /json/ACS_RBA_TRIODOS_IAT.json
-- Template file: /templates/ACS_RBA_template_v2.j2

USE `H0G_RBA`;

SET @service = 'ACS_U5G';
SET @issuer = '10000';
-- -----------------------------------------------------------------------------
-- INSERT of rulesets linked to :
-- service   : ACS_U5G
-- issuer    : 10000
-- subissuer : *
-- -----------------------------------------------------------------------------

SET @subIssuer = NULL;

-- -------- ISSUER_CONFIG TABLE -------- --

INSERT INTO `ISSUER_CONFIG` (`interface_type`, `is_active`, `service`, `issuer`, `sub_issuer`, `origin_priority`, `relevant_score`, `always_retrieve_external_scoring`, `default_score`, `default_decision`, `trustedbeneficiaries_active`, `eligible_merchant_active`, `skip_counters`, `bypass_3ds1`, `created_time`, `updated_time`, `deleted_time`)
VALUES ('THREE_DS',1 , @service, @issuer, @subIssuer, 'EXTERNAL', 1, 1, 85, 'SCA', 0, 0, 0, 0, now(), NULL, NULL)
ON DUPLICATE KEY UPDATE 
`interface_type`  ='THREE_DS',
`is_active`       =1,
`service`         =@service,
`origin_priority` ='EXTERNAL',
`relevant_score`  =1,
`always_retrieve_external_scoring` =1,
`default_score`   =85,
`default_decision`='SCA',
`trustedbeneficiaries_active`=0,
`eligible_merchant_active`=0,
`skip_counters`   =0,
`bypass_3ds1`     =0;

SELECT ID FROM `ISSUER_CONFIG` WHERE `issuer` = @issuer AND `sub_issuer` is NULL ORDER BY id DESC LIMIT 1 INTO @issuerConfigId;

INSERT INTO `SCORING_PROVIDER` (`issuer_config_id`, `is_active`, `ordinal`, `score_type`, `provider_type`, `score_service_url`, `advice_service_url`, `bypass_npa`, `created_time`, `updated_time`, `deleted_time`) VALUES
(@issuerConfigId, 1, 1, 'EXTERNAL/DS', 'INFORM', 'https://rss-ewl-internal-dev.inform-software.com:3334/services/AuthHubRBAService/RBArequest', 'https://rss-ewl-internal-dev.inform-software.com:3334/services/AuthHubAdviceService/RBArequest', 0, now(), NULL, NULL)
ON DUPLICATE KEY UPDATE
`is_active`=1,
`ordinal`=1,
`score_type`='EXTERNAL/DS',
`provider_type`='INFORM',
`score_service_url`='https://rss-ewl-internal-dev.inform-software.com:3334/services/AuthHubRBAService/RBArequest',
`advice_service_url`='https://rss-ewl-internal-dev.inform-software.com:3334/services/AuthHubAdviceService/RBArequest',
`bypass_npa`=0;
-- ---------------------------------
-- RULESET 3DS2_NON-EEA
-- ---------------------------------
-- ------ RULE_SET TABLE -------- --
INSERT INTO `RULE_SET` (issuer, subissuer, service, transaction_type, card_scheme,device_channel, location, created_time, updated_time, deleted_time) VALUES
(@issuer, @subIssuer, @service, NULL, NULL, NULL, NULL, NOW(), NULL, NULL);

SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type is NULL AND card_scheme is NULL AND device_channel is NULL  AND location is NULL ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

-- -------- RULE TABLE -------- --
INSERT INTO `RULE` (rule_set_id, name, ordinal, active, auth_type, reason_type, created_time, updated_time, deleted_time) VALUES
(@rule_set_id, 'TRN_SCORING_LOW_VALUE'  ,           1  , 1   , 'FRICTIONLESS' ,'LOW_SCORE'        ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SCORING_HIGH_VALUE' ,           2  , 1   , 'SCA'          ,'HIGH_SCORE'       ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SCORING_MID_VALUE'  ,           3  , 1   , 'SCA'          ,'MID_SCORE'        ,   now(), NULL, NULL),
(@rule_set_id, 'DEFAULT_AUTHENT'                   ,4  , NULL, 'SCA'          ,'NO_RULES'         ,   now(), NULL, NULL);


SELECT id FROM `RULE` WHERE name='TRN_SCORING_LOW_VALUE'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SCORING_LOW_VALUE;
SELECT id FROM `RULE` WHERE name='TRN_SCORING_HIGH_VALUE'                    AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SCORING_HIGH_VALUE;
SELECT id FROM `RULE` WHERE name='TRN_SCORING_MID_VALUE'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SCORING_MID_VALUE;
SELECT id FROM `RULE` WHERE name='DEFAULT_AUTHENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT;

-- -------- RULE CONDITION -------- --
INSERT INTO `RULE_CONDITION` (rule_id, name, created_time, updated_time, deleted_time) VALUES
(@rule_id_rs_3DS2_EEA_TRN_SCORING_LOW_VALUE                    , 'C1_SCA_SCORE'                   ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SCORING_HIGH_VALUE                   , 'C1_SCA_SCORE'                   ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SCORING_MID_VALUE                    , 'C1_SCA_SCORE'                   ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT                          , 'C0_DEFAULT_AUTHENT'             ,  now(), NULL, NULL);

-- Get the Rule Conditions ids.
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SCORING_LOW_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_12_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SCORING_HIGH_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_13_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SCORING_MID_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_14_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_30_id;

-- -------- OPERAND_VALUE TABLE -------- --
INSERT INTO `OPERAND_VALUE`(`label`,`value`,`rule_set_id`) VALUES
('True value'                   , 1     , @rule_set_id),
('ETV'                          , 10000 , @rule_set_id),
('LV'                           , 3000  , @rule_set_id),
('LOW_SCORE'                    , 20    , @rule_set_id),
('HIGH_SCORE'                   , 85    , @rule_set_id),
('DEFAULT'                      , 0     , @rule_set_id);
-- -------- OPERAND TABLE -------- --
INSERT INTO `OPERAND` (condition_id, name, type, operand_value_label, reversed, created_time, updated_time, deleted_time)
 VALUES
(@rule_condition_12_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 0  , now(), NULL, NULL),
(@rule_condition_12_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'ETV'            , 1  , now(), NULL, NULL),
(@rule_condition_12_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'LOW_SCORE'      , 1  , now(), NULL, NULL),
(@rule_condition_13_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 0  , now(), NULL, NULL),
(@rule_condition_13_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'ETV'            , 1  , now(), NULL, NULL),
(@rule_condition_13_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'HIGH_SCORE'     , 0  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 0  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'ETV'            , 1  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'HIGH_SCORE'     , 1  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'LOW_SCORE'      , 0  , now(), NULL, NULL),
(@rule_condition_30_id, 'DEFAULT'                      , 'DEFAULT'       , 'DEFAULT'        , 0  , now(), NULL, NULL);


-- ---------------------------------
-- RULESET 3DS2_EEA
-- ---------------------------------
-- ------ RULE_SET TABLE -------- --
INSERT INTO `RULE_SET` (issuer, subissuer, service, transaction_type, card_scheme,device_channel, location, created_time, updated_time, deleted_time) VALUES
(@issuer, @subIssuer, @service, NULL, NULL, NULL, 'EEA', NOW(), NULL, NULL);

SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type is NULL AND card_scheme is NULL AND device_channel is NULL  AND location = 'EEA' ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

-- -------- RULE TABLE -------- --
INSERT INTO `RULE` (rule_set_id, name, ordinal, active, auth_type, reason_type, created_time, updated_time, deleted_time) VALUES
(@rule_set_id, 'TRN_ID&V'               ,           1  , 1   , 'SCA'          ,'ID_V_SCA_REQ'     ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_FIRST_REC_PAYMENT'  ,           2  , 1   , 'SCA'          ,'FIRST_RECURRING'  ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SUB_REC_PAYMENT'    ,           3  , 1   , 'FRICTIONLESS' ,'RECURRING'        ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_FIRST_INS_PAYMENT'  ,           4  , 1   , 'SCA'          ,'FIRST_INSTALMENT' ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SUB_INS_PAYMENT'    ,           5  , 1   , 'FRICTIONLESS' ,'INSTALMENT'       ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_ACQ_EXEMPTION'      ,           6  , 1   , 'FRICTIONLESS' ,'ACQ_EXEMPTION'    ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SEC_CORPORATE'      ,           7  , 1   , 'FRICTIONLESS' ,'SEC_CORPORATE'    ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_ACQ_SCA_REQ'        ,           8  , 1   , 'SCA'          ,'ACQ_SCA_REQ'      ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_MAX_LOW_VALUE'      ,           9  , 1   , 'FRICTIONLESS' ,'LOW_VALUE'        ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SUM_LOW_VALUE'      ,           10  , 1   , 'FRICTIONLESS' ,'LOW_VALUE'        ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_HIGH_VALUE'         ,           11  , 1   , 'SCA'          ,'HIGH_VALUE'       ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SCORING_LOW_VALUE'  ,           12  , 1   , 'FRICTIONLESS' ,'LOW_SCORE'        ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SCORING_HIGH_VALUE' ,           13  , 1   , 'SCA'          ,'HIGH_SCORE'       ,   now(), NULL, NULL),
(@rule_set_id, 'TRN_SCORING_MID_VALUE'  ,           14  , 1   , 'SCA'          ,'MID_SCORE'        ,   now(), NULL, NULL),
(@rule_set_id, 'DEFAULT_LOW_VALUE'      ,           15  , 1   , 'SCA'          ,'MAX_FRICTIONLESS' ,   now(), NULL, NULL),
(@rule_set_id, 'DEFAULT_AUTHENT'                   ,16  , NULL, 'SCA'          ,'NO_RULES'         ,   now(), NULL, NULL);


SELECT id FROM `RULE` WHERE name='TRN_ID&V'                                  AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_IDV;
SELECT id FROM `RULE` WHERE name='TRN_FIRST_REC_PAYMENT'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_FIRST_REC_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_SUB_REC_PAYMENT'                       AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SUB_REC_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_FIRST_INS_PAYMENT'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_FIRST_INS_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_SUB_INS_PAYMENT'                       AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SUB_INS_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_ACQ_EXEMPTION'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_ACQ_EXEMPTION;
SELECT id FROM `RULE` WHERE name='TRN_SEC_CORPORATE'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SEC_CORPORATE;
SELECT id FROM `RULE` WHERE name='TRN_ACQ_SCA_REQ'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_ACQ_SCA_REQ;
SELECT id FROM `RULE` WHERE name='TRN_MAX_LOW_VALUE'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_MAX_LOW_VALUE;
SELECT id FROM `RULE` WHERE name='TRN_SUM_LOW_VALUE'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SUM_LOW_VALUE;
SELECT id FROM `RULE` WHERE name='TRN_HIGH_VALUE'                            AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_HIGH_VALUE;
SELECT id FROM `RULE` WHERE name='TRN_SCORING_LOW_VALUE'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SCORING_LOW_VALUE;
SELECT id FROM `RULE` WHERE name='TRN_SCORING_HIGH_VALUE'                    AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SCORING_HIGH_VALUE;
SELECT id FROM `RULE` WHERE name='TRN_SCORING_MID_VALUE'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_TRN_SCORING_MID_VALUE;
SELECT id FROM `RULE` WHERE name='DEFAULT_LOW_VALUE'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_DEFAULT_LOW_VALUE;
SELECT id FROM `RULE` WHERE name='DEFAULT_AUTHENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT;

-- -------- RULE CONDITION -------- --
INSERT INTO `RULE_CONDITION` (rule_id, name, created_time, updated_time, deleted_time) VALUES
(@rule_id_rs_3DS2_EEA_TRN_IDV                                  , 'C0_ID&V'                        ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_FIRST_REC_PAYMENT                    , 'C0_FIRST_REC_PAYMENT'           ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SUB_REC_PAYMENT                      , 'C0_SUB_REC_PAYMENT'             ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_FIRST_INS_PAYMENT                    , 'C0_FIRST_INS_PAYMENT'           ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SUB_INS_PAYMENT                      , 'C0_SUB_INS_PAYMENT'             ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_ACQ_EXEMPTION                        , 'C0_ACQ_EXEMPTION'               ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SEC_CORPORATE                        , 'C0_SEC_CORPORATE'               ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_ACQ_SCA_REQ                          , 'C0_ACQ_SCA_REQ'                 ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_MAX_LOW_VALUE                        , 'C0_FRICTIONLESS_AMOUNT_MAX'     ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SUM_LOW_VALUE                        , 'C0_FRICTIONLESS_AMOUNT_SUM'     ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_HIGH_VALUE                           , 'C0_SCA_AMOUNT'                  ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SCORING_LOW_VALUE                    , 'C1_SCA_SCORE'                   ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SCORING_HIGH_VALUE                   , 'C1_SCA_SCORE'                   ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_TRN_SCORING_MID_VALUE                    , 'C1_SCA_SCORE'                   ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_DEFAULT_LOW_VALUE                        , 'C0_FRICTIONLESS_AMOUNT'         ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT                          , 'C0_DEFAULT_AUTHENT'             ,  now(), NULL, NULL);

-- Get the Rule Conditions ids.
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_IDV ORDER BY id DESC LIMIT 1 INTO @rule_condition_1_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_FIRST_REC_PAYMENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_2_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SUB_REC_PAYMENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_3_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_FIRST_INS_PAYMENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_4_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SUB_INS_PAYMENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_5_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_ACQ_EXEMPTION ORDER BY id DESC LIMIT 1 INTO @rule_condition_6_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SEC_CORPORATE ORDER BY id DESC LIMIT 1 INTO @rule_condition_7_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_ACQ_SCA_REQ ORDER BY id DESC LIMIT 1 INTO @rule_condition_8_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_MAX_LOW_VALUE  ORDER BY id DESC LIMIT 1 INTO @rule_condition_9_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SUM_LOW_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_10_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_HIGH_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_11_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SCORING_LOW_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_12_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SCORING_HIGH_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_13_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_TRN_SCORING_MID_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_14_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_DEFAULT_LOW_VALUE ORDER BY id DESC LIMIT 1 INTO @rule_condition_15_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_30_id;

-- -------- OPERAND_VALUE TABLE -------- --
INSERT INTO `OPERAND_VALUE`(`label`,`value`,`rule_set_id`) VALUES
('02 (MESSAGE_CATEGORY)'        , 2     , @rule_set_id),
('06 (AUTHENTICATION_INDICATOR)', 6     , @rule_set_id),
('True value'                   , 1     , @rule_set_id),
('MAX_FRICT'                    , 5     , @rule_set_id),
('SUM_FRICT'                    , 10000 , @rule_set_id),
('ETV'                          , 10000 , @rule_set_id),
('LV'                           , 3000  , @rule_set_id),
('LOW_SCORE'                    , 20    , @rule_set_id),
('HIGH_SCORE'                   , 85    , @rule_set_id),
('DEFAULT'                      , 0     , @rule_set_id);
-- -------- OPERAND TABLE -------- --
INSERT INTO `OPERAND` (condition_id, name, type, operand_value_label, reversed, created_time, updated_time, deleted_time)
 VALUES
(@rule_condition_1_id, 'MESSAGE_CATEGORY'              , 'EQUALS'        , '02 (MESSAGE_CATEGORY)', 0, now(), NULL, NULL),
(@rule_condition_1_id, 'AUTHENTICATION_INDICATOR'      , 'EQUALS'        , '06 (AUTHENTICATION_INDICATOR)', 0, now(), NULL, NULL),
(@rule_condition_2_id, 'FIRST_RECURRING'               , 'STATUS'        , 'True value'     , 0  , now(), NULL, NULL),
(@rule_condition_3_id, 'RECURRING'                     , 'STATUS'        , 'True value'     , 0  , now(), NULL, NULL),
(@rule_condition_4_id, 'FIRST_INSTALMENT'              , 'STATUS'        , 'True value'     , 0  , now(), NULL, NULL),
(@rule_condition_5_id, 'INSTALMENT'                    , 'STATUS'        , 'True value'     , 0  , now(), NULL, NULL),
(@rule_condition_6_id, 'ACQ_EXEMPTION'                 , 'STATUS'        , 'True value'     , 0  , now(), NULL, NULL),
(@rule_condition_7_id, 'SEC_CORPORATE'                 , 'STATUS'        , 'True value'     , 0  , now(), NULL, NULL),
(@rule_condition_8_id, 'ACQ_SCA_REQ'                   , 'STATUS'        , 'True value'     , 0  , now(), NULL, NULL),
(@rule_condition_9_id, 'THRESHOLD_AMOUNT'              , 'STRICTLY_ABOVE', 'LV'             , 1  , now(), NULL, NULL),
(@rule_condition_9_id, 'FRICTIONLESS_TRN_COUNT'        , 'STRICTLY_UNDER', 'MAX_FRICT'      , 0  , now(), NULL, NULL),
(@rule_condition_10_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 1  , now(), NULL, NULL),
(@rule_condition_10_id, 'FRICTIONLESS_TRN_TOTAL_AMOUNT', 'STRICTLY_UNDER', 'SUM_FRICT'      , 0  , now(), NULL, NULL),
(@rule_condition_11_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'ETV'            , 0  , now(), NULL, NULL),
(@rule_condition_12_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 0  , now(), NULL, NULL),
(@rule_condition_12_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'ETV'            , 1  , now(), NULL, NULL),
(@rule_condition_12_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'LOW_SCORE'      , 1  , now(), NULL, NULL),
(@rule_condition_13_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 0  , now(), NULL, NULL),
(@rule_condition_13_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'ETV'            , 1  , now(), NULL, NULL),
(@rule_condition_13_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'HIGH_SCORE'     , 0  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 0  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'ETV'            , 1  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'HIGH_SCORE'     , 1  , now(), NULL, NULL),
(@rule_condition_14_id, 'THRESHOLD_SCORE'              , 'STRICTLY_ABOVE', 'LOW_SCORE'      , 0  , now(), NULL, NULL),
(@rule_condition_15_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_ABOVE', 'LV'             , 1  , now(), NULL, NULL),
(@rule_condition_30_id, 'DEFAULT'                      , 'DEFAULT'       , 'DEFAULT'        , 0  , now(), NULL, NULL);


-- ---------------------------------
-- RULESET 3RI_NON-EEA_VISA
-- ---------------------------------
-- ------ RULE_SET TABLE -------- --
INSERT INTO `RULE_SET` (issuer, subissuer, service, transaction_type, card_scheme,device_channel, location, created_time, updated_time, deleted_time) VALUES
(@issuer, @subIssuer, @service, 'PROT_2X_3DS', 'VISA', '03', NULL, NOW(), NULL, NULL);

SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'VISA' AND device_channel = '03'  AND location is NULL ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

-- -------- RULE TABLE -------- --
INSERT INTO `RULE` (rule_set_id, name, ordinal, active, auth_type, reason_type, created_time, updated_time, deleted_time) VALUES
(@rule_set_id, 'TRN_3RI_DECOUPLED'                 ,1  , 0, 'SCA'         , 'THREE_RI_DECOUPLED' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_REC_PAYMENT'                   ,2  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED',  now(), NULL, NULL),
(@rule_set_id, 'TRN_INS_PAYMENT'                   ,3  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED',  now(), NULL, NULL),
(@rule_set_id, 'TRN_ADD_CARD'                      ,4  , 0, 'SCA'         , 'THREE_RI_SCA_ADD_CARD',  now(), NULL, NULL),
(@rule_set_id, 'TRN_MAIN_CARD_INFO'                ,5  , 0, 'FRICTIONLESS', 'THREE_RI_CARDINFO'  ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_ACCOUNT_VERIFICATION'          ,6  , 0, 'FRICTIONLESS', 'THREE_RI_ACCOUNT'   ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_TOP_UP'                        ,7  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED'  ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_MOTO'                          ,8  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED'      ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_WHITELIST'                     ,9  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_OTHER_PAYMENT'                 ,10  , 0, 'FRICTIONLESS', 'THREE_RI_PAYMENT'   ,  now(), NULL, NULL),
(@rule_set_id, 'DEFAULT_AUTHENT'                   ,11  , NULL, 'DECLINE'      ,'THREE_RI_NOT_SUPPORTED',   now(), NULL, NULL);


SELECT id FROM `RULE` WHERE name='TRN_REC_PAYMENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_REC_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_INS_PAYMENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_INS_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_3RI_DECOUPLED'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_DECOUPLED;
SELECT id FROM `RULE` WHERE name='TRN_MOTO'                                  AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_MOTO;
SELECT id FROM `RULE` WHERE name='TRN_WHITELIST'                             AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_WHITELIST;
SELECT id FROM `RULE` WHERE name='TRN_MAIN_CARD_INFO' 						 AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_CARDINFO;
SELECT id FROM `RULE` WHERE name='TRN_ACCOUNT_VERIFICATION'                  AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_ACCOUNT_VERIFICATION;
SELECT id FROM `RULE` WHERE name='TRN_TOP_UP'                                AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_TOP_UP;
SELECT id FROM `RULE` WHERE name='TRN_ADD_CARD'                              AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_ADD_CARD_RULE;
SELECT id FROM `RULE` WHERE name='TRN_OTHER_PAYMENT'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_PAYMENT_RULE;
SELECT id FROM `RULE` WHERE name='DEFAULT_AUTHENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT;

-- -------- RULE CONDITION -------- --
INSERT INTO `RULE_CONDITION` (rule_id, name, created_time, updated_time, deleted_time) VALUES
(@rule_id_rs_3RI_DECOUPLED                                     , 'C0_3RI_DECOUPLED'               ,  now(), NULL, NULL),
(@rule_id_rs_3RI_REC_PAYMENT                                   , 'C0_REC_PAYMENT'                 ,  now(), NULL, NULL),
(@rule_id_rs_3RI_INS_PAYMENT                                   , 'C0_INS_PAYMENT'                 ,  now(), NULL, NULL),
(@rule_id_rs_3RI_ADD_CARD_RULE                                 , 'C0_ADD_CARD'                    ,  now(), NULL, NULL),
(@rule_id_rs_3RI_CARDINFO                                      , 'C0_MAIN_CARD_INFO'              ,  now(), NULL, NULL),
(@rule_id_rs_ACCOUNT_VERIFICATION                              , 'C0_ACCOUNT_VERIFICATION'        ,  now(), NULL, NULL),
(@rule_id_rs_TOP_UP                                            , 'C0_TOP_UP'                      ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C0_MOTO_MO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C1_MOTO_TO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_WHITELIST                                     , 'C0_WHITELIST'                   ,  now(), NULL, NULL),
(@rule_id_rs_3RI_PAYMENT_RULE                                  , 'C0_OTHER_PAYMENT'               ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT                          , 'C0_DEFAULT_AUTHENT'             ,  now(), NULL, NULL);

-- Get the Rule Conditions ids.
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_REC_PAYMENT AND name = 'C0_REC_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_20_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_INS_PAYMENT AND name = 'C0_INS_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_21_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_DECOUPLED AND name = 'C0_3RI_DECOUPLED' ORDER BY id DESC LIMIT 1 INTO @rule_condition_22_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C0_MOTO_MO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C1_MOTO_TO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_2_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_WHITELIST AND name = 'C0_WHITELIST' ORDER BY id DESC LIMIT 1 INTO @rule_condition_24_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_CARDINFO AND name = 'C0_MAIN_CARD_INFO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_25_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_ACCOUNT_VERIFICATION AND name = 'C0_ACCOUNT_VERIFICATION' ORDER BY id DESC LIMIT 1 INTO @rule_condition_26_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_TOP_UP AND name = 'C0_TOP_UP' ORDER BY id DESC LIMIT 1 INTO @rule_condition_27_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_ADD_CARD_RULE AND name = 'C0_ADD_CARD' ORDER BY id DESC LIMIT 1 INTO @rule_condition_28_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_PAYMENT_RULE AND name = 'C0_OTHER_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_29_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_30_id;

-- -------- OPERAND_VALUE TABLE -------- --
INSERT INTO `OPERAND_VALUE`(`label`,`value`,`rule_set_id`) VALUES
('True value'                   , 1     , @rule_set_id),
('1 (3RI IND)'                  , 1     , @rule_set_id),
('2 (3RI IND)'                  , 2     , @rule_set_id),
('3 (3RI IND)'                  , 3     , @rule_set_id),
('4 (3RI IND)'                  , 4     , @rule_set_id),
('5 (3RI IND)'                  , 5     , @rule_set_id),
('7 (3RI IND)'                  , 7     , @rule_set_id),
('8 (3RI IND)'                  , 8     , @rule_set_id),
('9 (3RI IND)'                  , 9     , @rule_set_id),
('10 (3RI IND)'                 ,10     , @rule_set_id),
('11 (3RI IND)'                 ,11     , @rule_set_id),
('DEFAULT'                      , 0     , @rule_set_id);
-- -------- OPERAND TABLE -------- --
INSERT INTO `OPERAND` (condition_id, name, type, operand_value_label, reversed, created_time, updated_time, deleted_time)
 VALUES
(@rule_condition_20_id, 'THREE_RI_IND'                 , 'EQUALS', '1 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_21_id, 'THREE_RI_IND'                 , 'EQUALS', '2 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_22_id, 'THREE_RI_DECOUPLED'           , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_23_id, 'THREE_RI_IND'                 , 'EQUALS', '8 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_23_2_id, 'THREE_RI_IND'               , 'EQUALS', '9 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_24_id, 'THREE_RI_WHITELIST'           , 'EQUALS', '10 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_25_id, 'THREE_RI_CARDINFO'            , 'EQUALS', '4 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_26_id, 'THREE_RI_IND'                 , 'EQUALS', '5 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_27_id, 'THREE_RI_IND'                 , 'EQUALS', '7 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_28_id, 'THREE_RI_IND'                 , 'EQUALS', '3 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'THREE_RI_IND'                 , 'EQUALS', '11 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_REFERENCE'              , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_CURRENCY'               , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_AMOUNT_EQ'              , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_AMOUNT_LEQ'             , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'MERCHANT_MCC'                 , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_30_id, 'DEFAULT'                      , 'DEFAULT'       , 'DEFAULT'        , 0  , now(), NULL, NULL);


-- ---------------------------------
-- RULESET 3RI_NON-EEA_MASTERCARD
-- ---------------------------------
-- ------ RULE_SET TABLE -------- --
INSERT INTO `RULE_SET` (issuer, subissuer, service, transaction_type, card_scheme,device_channel, location, created_time, updated_time, deleted_time) VALUES
(@issuer, @subIssuer, @service, 'PROT_2X_3DS', 'MASTERCARD', '03', NULL, NOW(), NULL, NULL);

SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'MASTERCARD' AND device_channel = '03'  AND location is NULL ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

-- -------- RULE TABLE -------- --
INSERT INTO `RULE` (rule_set_id, name, ordinal, active, auth_type, reason_type, created_time, updated_time, deleted_time) VALUES
(@rule_set_id, 'TRN_3RI_DECOUPLED'                 ,1  , 0, 'SCA'         , 'THREE_RI_DECOUPLED' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_REC_PAYMENT'               ,2  , 0, 'FRICTIONLESS', 'THREE_RI_RECURRING' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_INS_PAYMENT'               ,3  , 0, 'FRICTIONLESS', 'THREE_RI_INSTALMENT',  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_ADD_CARD_RULE'             ,4  , 0, 'DECLINE'     , 'THREE_RI_DECLINE_ADD_CARD',  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_CARDINFO'                  ,5  , 0, 'FRICTIONLESS', 'THREE_RI_CARDINFO'  ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_ACCOUNT_VERIFICATION'          ,6  , 0, 'FRICTIONLESS', 'THREE_RI_ACCOUNT'   ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_TOP_UP'                        ,7  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED',  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_MOTO_NO_DECOUPLED'         ,8  , 0, 'FRICTIONLESS', 'THREE_RI_MOTO'      ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_WHITELIST'                 ,9  , 0, 'FRICTIONLESS', 'THREE_RI_WHITELIST' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_PAYMENT_RULE'              ,10  , 0, 'FRICTIONLESS', 'THREE_RI_PAYMENT'   ,  now(), NULL, NULL),
(@rule_set_id, 'DEFAULT_AUTHENT'                   ,11  , NULL, 'DECLINE'      ,'THREE_RI_NOT_SUPPORTED',   now(), NULL, NULL);


SELECT id FROM `RULE` WHERE name='TRN_3RI_REC_PAYMENT'                       AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_REC_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_3RI_INS_PAYMENT'                       AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_INS_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_3RI_DECOUPLED'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_DECOUPLED;
SELECT id FROM `RULE` WHERE name='TRN_3RI_MOTO_NO_DECOUPLED'                 AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_MOTO;
SELECT id FROM `RULE` WHERE name='TRN_3RI_WHITELIST'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_WHITELIST;
SELECT id FROM `RULE` WHERE name='TRN_3RI_CARDINFO' 						 AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_CARDINFO;
SELECT id FROM `RULE` WHERE name='TRN_ACCOUNT_VERIFICATION'                  AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_ACCOUNT_VERIFICATION;
SELECT id FROM `RULE` WHERE name='TRN_TOP_UP'                                AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_TOP_UP;
SELECT id FROM `RULE` WHERE name='TRN_3RI_ADD_CARD_RULE'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_ADD_CARD_RULE;
SELECT id FROM `RULE` WHERE name='TRN_3RI_PAYMENT_RULE'                      AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_PAYMENT_RULE;
SELECT id FROM `RULE` WHERE name='DEFAULT_AUTHENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT;

-- -------- RULE CONDITION -------- --
INSERT INTO `RULE_CONDITION` (rule_id, name, created_time, updated_time, deleted_time) VALUES
(@rule_id_rs_3RI_DECOUPLED                                     , 'C0_3RI_DECOUPLED'               ,  now(), NULL, NULL),
(@rule_id_rs_3RI_REC_PAYMENT                                   , 'C0_3RI_REC_PAYMENT'             ,  now(), NULL, NULL),
(@rule_id_rs_3RI_INS_PAYMENT                                   , 'C0_3RI_INS_PAYMENT'             ,  now(), NULL, NULL),
(@rule_id_rs_3RI_ADD_CARD_RULE                                 , 'C0_3RI_ADD_CARD_RULE'           ,  now(), NULL, NULL),
(@rule_id_rs_3RI_CARDINFO                                      , 'C0_3RI_CARDINFO'                ,  now(), NULL, NULL),
(@rule_id_rs_ACCOUNT_VERIFICATION                              , 'C0_ACCOUNT_VERIFICATION'        ,  now(), NULL, NULL),
(@rule_id_rs_TOP_UP                                            , 'C0_TOP_UP'                      ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C0_MOTO_MO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C1_MOTO_TO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_WHITELIST                                     , 'C0_3RI_WHITELIST'               ,  now(), NULL, NULL),
(@rule_id_rs_3RI_PAYMENT_RULE                                  , 'C0_3RI_PAYMENT_RULE'            ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT                          , 'C0_DEFAULT_AUTHENT'             ,  now(), NULL, NULL);

-- Get the Rule Conditions ids.
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_REC_PAYMENT AND name = 'C0_3RI_REC_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_20_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_INS_PAYMENT AND name = 'C0_3RI_INS_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_21_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_DECOUPLED AND name = 'C0_3RI_DECOUPLED' ORDER BY id DESC LIMIT 1 INTO @rule_condition_22_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C0_MOTO_MO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C1_MOTO_TO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_2_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_WHITELIST AND name = 'C0_3RI_WHITELIST' ORDER BY id DESC LIMIT 1 INTO @rule_condition_24_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_CARDINFO AND name = 'C0_3RI_CARDINFO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_25_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_ACCOUNT_VERIFICATION AND name = 'C0_ACCOUNT_VERIFICATION' ORDER BY id DESC LIMIT 1 INTO @rule_condition_26_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_TOP_UP AND name = 'C0_TOP_UP' ORDER BY id DESC LIMIT 1 INTO @rule_condition_27_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_ADD_CARD_RULE AND name = 'C0_3RI_ADD_CARD_RULE' ORDER BY id DESC LIMIT 1 INTO @rule_condition_28_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_PAYMENT_RULE AND name = 'C0_3RI_PAYMENT_RULE' ORDER BY id DESC LIMIT 1 INTO @rule_condition_29_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_30_id;

-- -------- OPERAND_VALUE TABLE -------- --
INSERT INTO `OPERAND_VALUE`(`label`,`value`,`rule_set_id`) VALUES
('True value'                   , 1     , @rule_set_id),
('1 (3RI IND)'                  , 1     , @rule_set_id),
('2 (3RI IND)'                  , 2     , @rule_set_id),
('3 (3RI IND)'                  , 3     , @rule_set_id),
('4 (3RI IND)'                  , 4     , @rule_set_id),
('5 (3RI IND)'                  , 5     , @rule_set_id),
('7 (3RI IND)'                  , 7     , @rule_set_id),
('8 (3RI IND)'                  , 8     , @rule_set_id),
('9 (3RI IND)'                  , 9     , @rule_set_id),
('10 (3RI IND)'                 ,10     , @rule_set_id),
('11 (3RI IND)'                 ,11     , @rule_set_id),
('80 (TRUST_AMOUNT)'            ,80     , @rule_set_id),
('DEFAULT'                      , 0     , @rule_set_id);
-- -------- OPERAND TABLE -------- --
INSERT INTO `OPERAND` (condition_id, name, type, operand_value_label, reversed, created_time, updated_time, deleted_time)
 VALUES
(@rule_condition_20_id, 'THREE_RI_RECURRING'           , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_20_id, 'THREE_RI_IND'                 , 'EQUALS', '1 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_21_id, 'THREE_RI_INSTALMENT'          , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_21_id, 'THREE_RI_IND'                 , 'EQUALS', '2 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_22_id, 'THREE_RI_DECOUPLED'           , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_23_id, 'THREE_RI_IND'                 , 'EQUALS', '8 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_23_2_id, 'THREE_RI_IND'               , 'EQUALS', '9 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_24_id, 'THREE_RI_WHITELIST'           , 'EQUALS', '10 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_25_id, 'THREE_RI_CARDINFO'            , 'EQUALS', '4 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_26_id, 'THREE_RI_IND'                 , 'EQUALS', '5 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_27_id, 'THREE_RI_IND'                 , 'EQUALS', '7 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_28_id, 'THREE_RI_IND'                 , 'EQUALS', '3 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'THREE_RI_IND'                 , 'EQUALS', '11 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_UNDER', '80 (TRUST_AMOUNT)', 1, now(), NULL, NULL),
    
(@rule_condition_30_id, 'DEFAULT'                      , 'DEFAULT'       , 'DEFAULT'        , 0  , now(), NULL, NULL);


-- ---------------------------------
-- RULESET 3RI_EEA_VISA
-- ---------------------------------
-- ------ RULE_SET TABLE -------- --
INSERT INTO `RULE_SET` (issuer, subissuer, service, transaction_type, card_scheme,device_channel, location, created_time, updated_time, deleted_time) VALUES
(@issuer, @subIssuer, @service, 'PROT_2X_3DS', 'VISA', '03', 'EEA', NOW(), NULL, NULL);

SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'VISA' AND device_channel = '03'  AND location = 'EEA' ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

-- -------- RULE TABLE -------- --
INSERT INTO `RULE` (rule_set_id, name, ordinal, active, auth_type, reason_type, created_time, updated_time, deleted_time) VALUES
(@rule_set_id, 'TRN_3RI_DECOUPLED'                 ,1  , 0, 'SCA'         , 'THREE_RI_DECOUPLED' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_REC_PAYMENT'                   ,2  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED',  now(), NULL, NULL),
(@rule_set_id, 'TRN_INS_PAYMENT'                   ,3  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED',  now(), NULL, NULL),
(@rule_set_id, 'TRN_ADD_CARD'                      ,4  , 0, 'SCA'         , 'THREE_RI_SCA_ADD_CARD',  now(), NULL, NULL),
(@rule_set_id, 'TRN_MAIN_CARD_INFO'                ,5  , 0, 'FRICTIONLESS', 'THREE_RI_CARDINFO'  ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_ACCOUNT_VERIFICATION'          ,6  , 0, 'FRICTIONLESS', 'THREE_RI_ACCOUNT'   ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_TOP_UP'                        ,7  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED'  ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_MOTO'                          ,8  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED'      ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_WHITELIST'                     ,9  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_OTHER_PAYMENT'                 ,10  , 0, 'FRICTIONLESS', 'THREE_RI_PAYMENT'   ,  now(), NULL, NULL),
(@rule_set_id, 'DEFAULT_AUTHENT'                   ,11  , NULL, 'DECLINE'      ,'THREE_RI_NOT_SUPPORTED',   now(), NULL, NULL);


SELECT id FROM `RULE` WHERE name='TRN_REC_PAYMENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_REC_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_INS_PAYMENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_INS_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_3RI_DECOUPLED'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_DECOUPLED;
SELECT id FROM `RULE` WHERE name='TRN_MOTO'                                  AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_MOTO;
SELECT id FROM `RULE` WHERE name='TRN_WHITELIST'                             AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_WHITELIST;
SELECT id FROM `RULE` WHERE name='TRN_MAIN_CARD_INFO' 						 AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_CARDINFO;
SELECT id FROM `RULE` WHERE name='TRN_ACCOUNT_VERIFICATION'                  AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_ACCOUNT_VERIFICATION;
SELECT id FROM `RULE` WHERE name='TRN_TOP_UP'                                AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_TOP_UP;
SELECT id FROM `RULE` WHERE name='TRN_ADD_CARD'                              AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_ADD_CARD_RULE;
SELECT id FROM `RULE` WHERE name='TRN_OTHER_PAYMENT'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_PAYMENT_RULE;
SELECT id FROM `RULE` WHERE name='DEFAULT_AUTHENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT;

-- -------- RULE CONDITION -------- --
INSERT INTO `RULE_CONDITION` (rule_id, name, created_time, updated_time, deleted_time) VALUES
(@rule_id_rs_3RI_DECOUPLED                                     , 'C0_3RI_DECOUPLED'               ,  now(), NULL, NULL),
(@rule_id_rs_3RI_REC_PAYMENT                                   , 'C0_REC_PAYMENT'                 ,  now(), NULL, NULL),
(@rule_id_rs_3RI_INS_PAYMENT                                   , 'C0_INS_PAYMENT'                 ,  now(), NULL, NULL),
(@rule_id_rs_3RI_ADD_CARD_RULE                                 , 'C0_ADD_CARD'                    ,  now(), NULL, NULL),
(@rule_id_rs_3RI_CARDINFO                                      , 'C0_MAIN_CARD_INFO'              ,  now(), NULL, NULL),
(@rule_id_rs_ACCOUNT_VERIFICATION                              , 'C0_ACCOUNT_VERIFICATION'        ,  now(), NULL, NULL),
(@rule_id_rs_TOP_UP                                            , 'C0_TOP_UP'                      ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C0_MOTO_MO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C1_MOTO_TO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_WHITELIST                                     , 'C0_WHITELIST'                   ,  now(), NULL, NULL),
(@rule_id_rs_3RI_PAYMENT_RULE                                  , 'C0_OTHER_PAYMENT'               ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT                          , 'C0_DEFAULT_AUTHENT'             ,  now(), NULL, NULL);

-- Get the Rule Conditions ids.
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_REC_PAYMENT AND name = 'C0_REC_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_20_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_INS_PAYMENT AND name = 'C0_INS_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_21_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_DECOUPLED AND name = 'C0_3RI_DECOUPLED' ORDER BY id DESC LIMIT 1 INTO @rule_condition_22_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C0_MOTO_MO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C1_MOTO_TO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_2_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_WHITELIST AND name = 'C0_WHITELIST' ORDER BY id DESC LIMIT 1 INTO @rule_condition_24_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_CARDINFO AND name = 'C0_MAIN_CARD_INFO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_25_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_ACCOUNT_VERIFICATION AND name = 'C0_ACCOUNT_VERIFICATION' ORDER BY id DESC LIMIT 1 INTO @rule_condition_26_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_TOP_UP AND name = 'C0_TOP_UP' ORDER BY id DESC LIMIT 1 INTO @rule_condition_27_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_ADD_CARD_RULE AND name = 'C0_ADD_CARD' ORDER BY id DESC LIMIT 1 INTO @rule_condition_28_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_PAYMENT_RULE AND name = 'C0_OTHER_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_29_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_30_id;

-- -------- OPERAND_VALUE TABLE -------- --
INSERT INTO `OPERAND_VALUE`(`label`,`value`,`rule_set_id`) VALUES
('True value'                   , 1     , @rule_set_id),
('1 (3RI IND)'                  , 1     , @rule_set_id),
('2 (3RI IND)'                  , 2     , @rule_set_id),
('3 (3RI IND)'                  , 3     , @rule_set_id),
('4 (3RI IND)'                  , 4     , @rule_set_id),
('5 (3RI IND)'                  , 5     , @rule_set_id),
('7 (3RI IND)'                  , 7     , @rule_set_id),
('8 (3RI IND)'                  , 8     , @rule_set_id),
('9 (3RI IND)'                  , 9     , @rule_set_id),
('10 (3RI IND)'                 ,10     , @rule_set_id),
('11 (3RI IND)'                 ,11     , @rule_set_id),
('DEFAULT'                      , 0     , @rule_set_id);
-- -------- OPERAND TABLE -------- --
INSERT INTO `OPERAND` (condition_id, name, type, operand_value_label, reversed, created_time, updated_time, deleted_time)
 VALUES
(@rule_condition_20_id, 'THREE_RI_IND'                 , 'EQUALS', '1 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_21_id, 'THREE_RI_IND'                 , 'EQUALS', '2 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_22_id, 'THREE_RI_DECOUPLED'           , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_23_id, 'THREE_RI_IND'                 , 'EQUALS', '8 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_23_2_id, 'THREE_RI_IND'               , 'EQUALS', '9 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_24_id, 'THREE_RI_WHITELIST'           , 'EQUALS', '10 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_25_id, 'THREE_RI_CARDINFO'            , 'EQUALS', '4 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_26_id, 'THREE_RI_IND'                 , 'EQUALS', '5 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_27_id, 'THREE_RI_IND'                 , 'EQUALS', '7 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_28_id, 'THREE_RI_IND'                 , 'EQUALS', '3 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'THREE_RI_IND'                 , 'EQUALS', '11 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_REFERENCE'              , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_CURRENCY'               , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_AMOUNT_EQ'              , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'PRIOR_AMOUNT_LEQ'             , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'MERCHANT_MCC'                 , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_30_id, 'DEFAULT'                      , 'DEFAULT'       , 'DEFAULT'        , 0  , now(), NULL, NULL);


-- ---------------------------------
-- RULESET 3RI_EEA_MASTERCARD
-- ---------------------------------
-- ------ RULE_SET TABLE -------- --
INSERT INTO `RULE_SET` (issuer, subissuer, service, transaction_type, card_scheme,device_channel, location, created_time, updated_time, deleted_time) VALUES
(@issuer, @subIssuer, @service, 'PROT_2X_3DS', 'MASTERCARD', '03', 'EEA', NOW(), NULL, NULL);

SELECT id FROM RULE_SET WHERE issuer = @issuer AND subIssuer is NULL AND service = @service AND transaction_type = 'PROT_2X_3DS' AND card_scheme = 'MASTERCARD' AND device_channel = '03'  AND location = 'EEA' ORDER BY id DESC LIMIT 1 INTO @rule_set_id;

-- -------- RULE TABLE -------- --
INSERT INTO `RULE` (rule_set_id, name, ordinal, active, auth_type, reason_type, created_time, updated_time, deleted_time) VALUES
(@rule_set_id, 'TRN_3RI_DECOUPLED'                 ,1  , 0, 'SCA'         , 'THREE_RI_DECOUPLED' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_REC_PAYMENT'               ,2  , 0, 'FRICTIONLESS', 'THREE_RI_RECURRING' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_INS_PAYMENT'               ,3  , 0, 'FRICTIONLESS', 'THREE_RI_INSTALMENT',  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_ADD_CARD_RULE'             ,4  , 0, 'DECLINE'     , 'THREE_RI_DECLINE_ADD_CARD',  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_CARDINFO'                  ,5  , 0, 'FRICTIONLESS', 'THREE_RI_CARDINFO'  ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_ACCOUNT_VERIFICATION'          ,6  , 0, 'FRICTIONLESS', 'THREE_RI_ACCOUNT'   ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_TOP_UP'                        ,7  , 0, 'DECLINE'     , 'THREE_RI_NOT_SUPPORTED',  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_MOTO_NO_DECOUPLED'         ,8  , 0, 'FRICTIONLESS', 'THREE_RI_MOTO'      ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_WHITELIST'                 ,9  , 0, 'FRICTIONLESS', 'THREE_RI_WHITELIST' ,  now(), NULL, NULL),
(@rule_set_id, 'TRN_3RI_PAYMENT_RULE'              ,10  , 0, 'FRICTIONLESS', 'THREE_RI_PAYMENT'   ,  now(), NULL, NULL),
(@rule_set_id, 'DEFAULT_AUTHENT'                   ,11  , NULL, 'DECLINE'      ,'THREE_RI_NOT_SUPPORTED',   now(), NULL, NULL);


SELECT id FROM `RULE` WHERE name='TRN_3RI_REC_PAYMENT'                       AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_REC_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_3RI_INS_PAYMENT'                       AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_INS_PAYMENT;
SELECT id FROM `RULE` WHERE name='TRN_3RI_DECOUPLED'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_DECOUPLED;
SELECT id FROM `RULE` WHERE name='TRN_3RI_MOTO_NO_DECOUPLED'                 AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_MOTO;
SELECT id FROM `RULE` WHERE name='TRN_3RI_WHITELIST'                         AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_WHITELIST;
SELECT id FROM `RULE` WHERE name='TRN_3RI_CARDINFO' 						 AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_CARDINFO;
SELECT id FROM `RULE` WHERE name='TRN_ACCOUNT_VERIFICATION'                  AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_ACCOUNT_VERIFICATION;
SELECT id FROM `RULE` WHERE name='TRN_TOP_UP'                                AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_TOP_UP;
SELECT id FROM `RULE` WHERE name='TRN_3RI_ADD_CARD_RULE'                     AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_ADD_CARD_RULE;
SELECT id FROM `RULE` WHERE name='TRN_3RI_PAYMENT_RULE'                      AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3RI_PAYMENT_RULE;
SELECT id FROM `RULE` WHERE name='DEFAULT_AUTHENT'                           AND rule_set_id = @rule_set_id ORDER BY id DESC LIMIT 1 INTO @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT;

-- -------- RULE CONDITION -------- --
INSERT INTO `RULE_CONDITION` (rule_id, name, created_time, updated_time, deleted_time) VALUES
(@rule_id_rs_3RI_DECOUPLED                                     , 'C0_3RI_DECOUPLED'               ,  now(), NULL, NULL),
(@rule_id_rs_3RI_REC_PAYMENT                                   , 'C0_3RI_REC_PAYMENT'             ,  now(), NULL, NULL),
(@rule_id_rs_3RI_INS_PAYMENT                                   , 'C0_3RI_INS_PAYMENT'             ,  now(), NULL, NULL),
(@rule_id_rs_3RI_ADD_CARD_RULE                                 , 'C0_3RI_ADD_CARD_RULE'           ,  now(), NULL, NULL),
(@rule_id_rs_3RI_CARDINFO                                      , 'C0_3RI_CARDINFO'                ,  now(), NULL, NULL),
(@rule_id_rs_ACCOUNT_VERIFICATION                              , 'C0_ACCOUNT_VERIFICATION'        ,  now(), NULL, NULL),
(@rule_id_rs_TOP_UP                                            , 'C0_TOP_UP'                      ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C0_MOTO_MO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_MOTO                                          , 'C1_MOTO_TO'                     ,  now(), NULL, NULL),
(@rule_id_rs_3RI_WHITELIST                                     , 'C0_3RI_WHITELIST'               ,  now(), NULL, NULL),
(@rule_id_rs_3RI_PAYMENT_RULE                                  , 'C0_3RI_PAYMENT_RULE'            ,  now(), NULL, NULL),
(@rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT                          , 'C0_DEFAULT_AUTHENT'             ,  now(), NULL, NULL);

-- Get the Rule Conditions ids.
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_REC_PAYMENT AND name = 'C0_3RI_REC_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_20_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_INS_PAYMENT AND name = 'C0_3RI_INS_PAYMENT' ORDER BY id DESC LIMIT 1 INTO @rule_condition_21_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_DECOUPLED AND name = 'C0_3RI_DECOUPLED' ORDER BY id DESC LIMIT 1 INTO @rule_condition_22_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C0_MOTO_MO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_MOTO AND name = 'C1_MOTO_TO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_23_2_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_WHITELIST AND name = 'C0_3RI_WHITELIST' ORDER BY id DESC LIMIT 1 INTO @rule_condition_24_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_CARDINFO AND name = 'C0_3RI_CARDINFO' ORDER BY id DESC LIMIT 1 INTO @rule_condition_25_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_ACCOUNT_VERIFICATION AND name = 'C0_ACCOUNT_VERIFICATION' ORDER BY id DESC LIMIT 1 INTO @rule_condition_26_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_TOP_UP AND name = 'C0_TOP_UP' ORDER BY id DESC LIMIT 1 INTO @rule_condition_27_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_ADD_CARD_RULE AND name = 'C0_3RI_ADD_CARD_RULE' ORDER BY id DESC LIMIT 1 INTO @rule_condition_28_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3RI_PAYMENT_RULE AND name = 'C0_3RI_PAYMENT_RULE' ORDER BY id DESC LIMIT 1 INTO @rule_condition_29_id;
SELECT id FROM `RULE_CONDITION` WHERE rule_id = @rule_id_rs_3DS2_EEA_DEFAULT_AUTHENT ORDER BY id DESC LIMIT 1 INTO @rule_condition_30_id;

-- -------- OPERAND_VALUE TABLE -------- --
INSERT INTO `OPERAND_VALUE`(`label`,`value`,`rule_set_id`) VALUES
('True value'                   , 1     , @rule_set_id),
('1 (3RI IND)'                  , 1     , @rule_set_id),
('2 (3RI IND)'                  , 2     , @rule_set_id),
('3 (3RI IND)'                  , 3     , @rule_set_id),
('4 (3RI IND)'                  , 4     , @rule_set_id),
('5 (3RI IND)'                  , 5     , @rule_set_id),
('7 (3RI IND)'                  , 7     , @rule_set_id),
('8 (3RI IND)'                  , 8     , @rule_set_id),
('9 (3RI IND)'                  , 9     , @rule_set_id),
('10 (3RI IND)'                 ,10     , @rule_set_id),
('11 (3RI IND)'                 ,11     , @rule_set_id),
('80 (TRUST_AMOUNT)'            ,80     , @rule_set_id),
('DEFAULT'                      , 0     , @rule_set_id);
-- -------- OPERAND TABLE -------- --
INSERT INTO `OPERAND` (condition_id, name, type, operand_value_label, reversed, created_time, updated_time, deleted_time)
 VALUES
(@rule_condition_20_id, 'THREE_RI_RECURRING'           , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_20_id, 'THREE_RI_IND'                 , 'EQUALS', '1 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_21_id, 'THREE_RI_INSTALMENT'          , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_21_id, 'THREE_RI_IND'                 , 'EQUALS', '2 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_22_id, 'THREE_RI_DECOUPLED'           , 'STATUS', 'True value', 0, now(), NULL, NULL),
(@rule_condition_23_id, 'THREE_RI_IND'                 , 'EQUALS', '8 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_23_2_id, 'THREE_RI_IND'               , 'EQUALS', '9 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_24_id, 'THREE_RI_WHITELIST'           , 'EQUALS', '10 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_25_id, 'THREE_RI_CARDINFO'            , 'EQUALS', '4 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_26_id, 'THREE_RI_IND'                 , 'EQUALS', '5 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_27_id, 'THREE_RI_IND'                 , 'EQUALS', '7 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_28_id, 'THREE_RI_IND'                 , 'EQUALS', '3 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'THREE_RI_IND'                 , 'EQUALS', '11 (3RI IND)', 0, now(), NULL, NULL),
(@rule_condition_29_id, 'THRESHOLD_AMOUNT'             , 'STRICTLY_UNDER', '80 (TRUST_AMOUNT)', 1, now(), NULL, NULL),
    
(@rule_condition_30_id, 'DEFAULT'                      , 'DEFAULT'       , 'DEFAULT'        , 0  , now(), NULL, NULL);


