-- Generated by sql-script-generator
-- Version: 22R1-GE-3.5-SNAPSHOT
-- Date: Wed Sep 07 15:48:50 CEST 2022
-- Properties file: /json/Configuration_IAT.json
-- Template file: /templates/ACS_CR_H5G_issuer_global_template.j2

USE H5G_CREPO;
-- ------------------------
-- CR CONFIG FILE
-- service = ACS_U5G
-- issuer = 10000
-- ------------------------

-- Beginning of data insertion --

SELECT `code`, `label` FROM `Customer` ;

INSERT INTO `Customer` (`code`, `label`, `PARENT_ID`)
SELECT * FROM (SELECT '*', 'root', NULL) AS tmp
WHERE NOT EXISTS (
	SELECT label FROM `Customer` WHERE label = 'root'
) LIMIT 1;

INSERT INTO `Customer` (`code`, `label`, `PARENT_ID`)
SELECT * FROM (SELECT '10000', 'Triodos Bank', `id` FROM `Customer` WHERE `label` = 'root') AS tmp
WHERE NOT EXISTS (
	SELECT code FROM `Customer` WHERE code = '10000'
) LIMIT 1;

INSERT INTO `Customer` (`code`, `label`, `PARENT_ID`)
SELECT * FROM (SELECT '10006', 'Triodos BE', `id` FROM `Customer` WHERE `label` = 'Triodos Bank') AS tmp
WHERE NOT EXISTS (
	SELECT code FROM `Customer` WHERE code = '10006'
) LIMIT 1;

SELECT `code`, `label` FROM `Customer` ;

-- End of data insertion
