-- Generated by sql-script-generator
-- Version: 22R1-GE-3.5-SNAPSHOT
-- Date: Wed Sep 07 15:49:10 CEST 2022
-- Properties file: /json/Configuration_IAT.json
-- Template file: /templates/ACS_CR_H5G_ROLLBACK_template.j2

USE H5G_CREPO;
-- ------------------------
-- CR CONFIG FILE
-- service = ACS_U5G
-- issuer = 10000
-- ------------------------

-- Beginning of data deletion --

SELECT `code`, `label` FROM `Customer` ;

DELETE FROM `Customer`
WHERE code = '';

SELECT `code`, `label` FROM `Customer` ;

-- End of data deletion
