USE U2M_ACS_MONITOR;

UPDATE SERVICE_INFO SET ADDITIONAL_INFO = '
{ "machineInfo": {
        "tpacsk01b": {
                "additionalInfo": {
                        "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                        "flash.proxy.host": "proxy.brs.pci.eqwl.svc.meshcore.net",
                        "flash.proxy.port": "3128",
                        "flash.connect.timeout": "3000",
                        "flash.read.timeout": "3000",
                        "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                        "flash.key.store.type": "PKCS12",
                        "flash.key.store.password": "ignored",
                        "flash.initial.delay": "1000",
                        "flash.min.aleatory": "10",
                        "flash.max.aleatory": "100",
                        "flash.max.tryouts": "20",
                        "flash.coefficient": "2.0",
                        "flash.unsecure.mode": "false",
                        "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                        "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                },
                "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                "servicePort": null,
                "proxyHost": "proxy.brs.pci.eqwl.svc.meshcore.net",
                "proxyPort": "3128",
                "serverUrl": "https://ssl-prd-flash.as8677.net",
                "serviceStatus": "OK",
                "version": "2.5.1",
                "serviceStatusInfo": null,
                "serviceDependencies": []
        },
        "tpacsk02b": {
                "additionalInfo": {
                        "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                        "flash.proxy.host": "proxy.brs.pci.eqwl.svc.meshcore.net",
                        "flash.proxy.port": "3128",
                        "flash.connect.timeout": "3000",
                        "flash.read.timeout": "3000",
                        "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                        "flash.key.store.type": "PKCS12",
                        "flash.key.store.password": "ignored",
                        "flash.initial.delay": "1000",
                        "flash.min.aleatory": "10",
                        "flash.max.aleatory": "100",
                        "flash.max.tryouts": "20",
                        "flash.coefficient": "2.0",
                        "flash.unsecure.mode": "false",
                        "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                        "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                },
                "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                "servicePort": null,
                "proxyHost": "proxy.brs.pci.eqwl.svc.meshcore.net",
                "proxyPort": "3128",
                "serverUrl": "https://ssl-prd-flash.as8677.net",
                "serviceStatus": "OK",
                "version": "2.5.1",
                "serviceStatusInfo": null,
                "serviceDependencies": []
        },
        "tpacsk03b": {
                "additionalInfo": {
                        "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                        "flash.proxy.host": "proxy.brs.pci.eqwl.svc.meshcore.net",
                        "flash.proxy.port": "3128",
                        "flash.connect.timeout": "3000",
                        "flash.read.timeout": "3000",
                        "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                        "flash.key.store.type": "PKCS12",
                        "flash.key.store.password": "ignored",
                        "flash.initial.delay": "1000",
                        "flash.min.aleatory": "10",
                        "flash.max.aleatory": "100",
                        "flash.max.tryouts": "20",
                        "flash.coefficient": "2.0",
                        "flash.unsecure.mode": "false",
                        "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                        "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                },
                "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                "servicePort": null,
                "proxyHost": "proxy.brs.pci.eqwl.svc.meshcore.net",
                "proxyPort": "3128",
                "serverUrl": "https://ssl-prd-flash.as8677.net",
                "serviceStatus": "OK",
                "version": "2.5.1",
                "serviceStatusInfo": null,
                "serviceDependencies": []
        },
        "tpacsk04b": {
                "additionalInfo": {
                        "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                        "flash.proxy.host": "proxy.brs.pci.eqwl.svc.meshcore.net",
                        "flash.proxy.port": "3128",
                        "flash.connect.timeout": "3000",
                        "flash.read.timeout": "3000",
                        "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                        "flash.key.store.type": "PKCS12",
                        "flash.key.store.password": "ignored",
                        "flash.initial.delay": "1000",
                        "flash.min.aleatory": "10",
                        "flash.max.aleatory": "100",
                        "flash.max.tryouts": "20",
                        "flash.coefficient": "2.0",
                        "flash.unsecure.mode": "false",
                        "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                        "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                },
                "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                "servicePort": null,
                "proxyHost": "proxy.brs.pci.eqwl.svc.meshcore.net",
                "proxyPort": "3128",
                "serverUrl": "https://ssl-prd-flash.as8677.net",
                "serviceStatus": "OK",
                "version": "2.5.1",
                "serviceStatusInfo": null,
                "serviceDependencies": []
        }
}
'
WHERE SERVICE_NAME = 'flash' AND SITE_NAME = 'Brussels' AND ACS_ID = 'U7G';

UPDATE SERVICE_INFO SET ADDITIONAL_INFO = '{
        "machineInfo": {
                "tpacsk01v": {
                        "additionalInfo": {
                                "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                                "flash.proxy.host": "proxy.vdm.pci.priv.atos.fr",
                                "flash.proxy.port": "3128",
                                "flash.connect.timeout": "3000",
                                "flash.read.timeout": "3000",
                                "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                                "flash.key.store.type": "PKCS12",
                                "flash.key.store.password": "ignored",
                                "flash.initial.delay": "1000",
                                "flash.min.aleatory": "10",
                                "flash.max.aleatory": "100",
                                "flash.max.tryouts": "20",
                                "flash.coefficient": "2.0",
                                "flash.unsecure.mode": "false",
                                "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                                "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                        },
                        "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                        "servicePort": null,
                        "proxyHost": "proxy.vdm.pci.priv.atos.fr",
                        "proxyPort": "3128",
                        "serverUrl": "https://ssl-prd-flash.as8677.net",
                        "serviceStatus": "OK",
                        "version": "2.5.1",
                        "serviceStatusInfo": null,
                        "serviceDependencies": []
                },
                "tpacsk02v": {
                        "additionalInfo": {
                                "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                                "flash.proxy.host": "proxy.vdm.pci.priv.atos.fr",
                                "flash.proxy.port": "3128",
                                "flash.connect.timeout": "3000",
                                "flash.read.timeout": "3000",
                                "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                                "flash.key.store.type": "PKCS12",
                                "flash.key.store.password": "ignored",
                                "flash.initial.delay": "1000",
                                "flash.min.aleatory": "10",
                                "flash.max.aleatory": "100",
                                "flash.max.tryouts": "20",
                                "flash.coefficient": "2.0",
                                "flash.unsecure.mode": "false",
                                "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                                "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                        },
                        "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                        "servicePort": null,
                        "proxyHost": "proxy.vdm.pci.priv.atos.fr",
                        "proxyPort": "3128",
                        "serverUrl": "https://ssl-prd-flash.as8677.net",
                        "serviceStatus": "OK",
                        "version": "2.5.1",
                        "serviceStatusInfo": null,
                        "serviceDependencies": []
                },
                "tpacsk03v": {
                        "additionalInfo": {
                                "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                                "flash.proxy.host": "proxy.vdm.pci.priv.atos.fr",
                                "flash.proxy.port": "3128",
                                "flash.connect.timeout": "3000",
                                "flash.read.timeout": "3000",
                                "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                                "flash.key.store.type": "PKCS12",
                                "flash.key.store.password": "ignored",
                                "flash.initial.delay": "1000",
                                "flash.min.aleatory": "10",
                                "flash.max.aleatory": "100",
                                "flash.max.tryouts": "20",
                                "flash.coefficient": "2.0",
                                "flash.unsecure.mode": "false",
                                "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                                "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                        },
                        "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                        "servicePort": null,
                        "proxyHost": "proxy.vdm.pci.priv.atos.fr",
                        "proxyPort": "3128",
                        "serverUrl": "https://ssl-prd-flash.as8677.net",
                        "serviceStatus": "OK",
                        "version": "2.5.1",
                        "serviceStatusInfo": null,
                        "serviceDependencies": []
                },
                "tpacsk04v": {
                        "additionalInfo": {
                                "flash.server.url": "https://ssl-prd-flash.as8677.net/flash",
                                "flash.proxy.host": "proxy.vdm.pci.priv.atos.fr",
                                "flash.proxy.port": "3128",
                                "flash.connect.timeout": "3000",
                                "flash.read.timeout": "3000",
                                "flash.key.store.file": "/MIDDLE/u7g_wlpacs/u7g-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/u7g.fo.wlp-acs.com.p12",
                                "flash.key.store.type": "PKCS12",
                                "flash.key.store.password": "ignored",
                                "flash.initial.delay": "1000",
                                "flash.min.aleatory": "10",
                                "flash.max.aleatory": "100",
                                "flash.max.tryouts": "20",
                                "flash.coefficient": "2.0",
                                "flash.unsecure.mode": "false",
                                "flash.collection.id.pages": "acs-ux-swisskey-u7g",
                                "flash.collection.id.session": "acs-authentication-swisskey-u7g"
                        },
                        "serviceUrl": "https://ssl-prd-flash.as8677.net/flash",
                        "servicePort": null,
                        "proxyHost": "proxy.vdm.pci.priv.atos.fr",
                        "proxyPort": "3128",
                        "serverUrl": "https://ssl-prd-flash.as8677.net",
                        "serviceStatus": "OK",
                        "version": "2.5.1",
                        "serviceStatusInfo": null,
                        "serviceDependencies": []
                }
        }
}'
WHERE SERVICE_NAME = 'flash' AND SITE_NAME = 'Vendome' AND ACS_ID = 'U7G';