USE `U5G_ACS_FO`;

DELETE FROM `PROFILE_SET` WHERE `ID` in (47,48);

DELETE FROM `ISSUER_CONFIG` WHERE `ISSUER_NAME` in ('VOLKSWAGEN_BANK', 'AUDI_BANK');

DELETE FROM `CRYPTO_CONFIG` WHERE `ID` = 15;

DELETE FROM `BIN_RANGE` WHERE `PROFILE_SET_ID` in (47,48);