USE PORTAL_SERVICE_PARAM;

/* Christian Schnur */
SET @userLogin = 'EWLA790281';

-- check existing 
SET @serviceName = 'ACS_U5G';
SET @serviceNamePortail = 'PORTAIL';
SET @roleName = 'ADMIN_SPARDA'; 

SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

-- insert any user by login to a specific role
SET @roleId = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
SET @serviceId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceName);
SET @servicePortailId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceNamePortail);

DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- check existing 
SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

USE PORTAL_SERVICE_PARAM;

-- check existing 
SET @serviceName = 'ACS_U5G';
SET @serviceNamePortail = 'PORTAIL';
SET @roleName = 'AGENT_SPARDA'; 

SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);


-- insert any user by login to a specific role
SET @roleId = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
SET @serviceId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceName);
SET @servicePortailId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceNamePortail);

DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- check existing 
SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

USE PORTAL_SERVICE_PARAM;

-- check existing 
SET @serviceName = 'ACS_U5G';
SET @serviceNamePortail = 'PORTAIL';
SET @roleName = 'SUPER_ADMIN_SPARDA'; 

SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

-- insert any user by login to a specific role
SET @roleId = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
SET @serviceId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceName);
SET @servicePortailId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceNamePortail);

DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- check existing 
SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
