USE U5G_ACS_FO;

SELECT * FROM CARDNETWORK;

UPDATE CARDNETWORK SET DS_REFERENCE_NUMBER = 'VisaReferenceNumber', ECI_AUTH_SUCCESS = '05', ECI_NPA_AUTH_SUCCESS = NULL, ECI_NO_AUTH = '06',ECI_FAILED = '07', ECI_NPA_FAILED = NULL, SOLUTION = 'Verified by VISA™', DISPLAY_NAME = 'VISA™', ACS_LOGIN_ID = 'Atos Worldline', VE_PUBLIC_URL = 'http://ve/', SECONDARY_DS_REFERENCE_NUMBER = NULL
WHERE NAME = 'VISA';

SELECT * FROM CARDNETWORK;
