/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

USE `U2M_ACS_MONITOR`;

DROP TABLE IF EXISTS `SERVICE_INFO`;
CREATE TABLE `SERVICE_INFO` (
  `SERVICE_NAME` VARCHAR(45) NOT NULL,
  `SITE_NAME` VARCHAR(45) NOT NULL,
  `ACS_ID` VARCHAR(45) NOT NULL DEFAULT 'ANY',
  `ADDITIONAL_INFO` TEXT NULL,
  `SCOPE` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`SERVICE_NAME`, `SITE_NAME`, `ACS_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;