/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

USE `U5G_ACS_FO`;

DROP TABLE IF EXISTS `BIN_RANGE`;
CREATE TABLE IF NOT EXISTS `BIN_RANGE` (
  `UPPER_BOUND` varchar(255) NOT NULL DEFAULT '',
  `LOWER_BOUND` varchar(255) NOT NULL DEFAULT '',
  `BINRANGE_KEY_ID` varchar(255) DEFAULT NULL,
  `CARD_NETWORKS` varchar(255) DEFAULT NULL,
  `SUB_ISSUER_CODE` varchar(255) NOT NULL,
  `CARDNETWORKS` varchar(255) DEFAULT NULL,
  `PAN_LENGTH` int(11) DEFAULT NULL,
  `SHARED_BINRANGE` tinyint(1) DEFAULT NULL,
  `PROFILE_SET_ID` varchar(255) DEFAULT NULL,
  `ACTIVATION_STATUS` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`UPPER_BOUND`,`LOWER_BOUND`,`SUB_ISSUER_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `CARDNETWORK`;
CREATE TABLE IF NOT EXISTS `CARDNETWORK` (
  `NAME` varchar(32) NOT NULL,
  `ECI_AUTH_SUCCESS` varchar(32) NOT NULL,
  `ECI_NO_AUTH` varchar(32) NOT NULL,
  `SOLUTION` varchar(45) DEFAULT NULL,
  `DISPLAY_NAME` varchar(32) NOT NULL,
  `ACS_LOGIN_ID` varchar(255) DEFAULT NULL,
  `VE_PUBLIC_URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* The column 'VE_PUBLIC_URL' needs to be adapted to the environment :
   - in local, you can use http://localhost:8120/acs-ve-service/
   - in internal acceptance, the url will be https://ssl-qlf-u5g-fo-acs-ve.wlp-acs.com
   - in external acceptance, the url will be https://ssl-liv-u5g-fo-acs-ve.wlp-acs.com
   - in production, the url will be https://ssl-prd-u5g-fo-acs-ve.wlp-acs.com
*/
/*!40000 ALTER TABLE `CARDNETWORK` DISABLE KEYS */;
INSERT INTO `CARDNETWORK` (`NAME`, `ECI_AUTH_SUCCESS`, `ECI_NO_AUTH`, `SOLUTION`, `DISPLAY_NAME`, `ACS_LOGIN_ID`, `VE_PUBLIC_URL`) VALUES
  ('MASTERCARD', '02', '01', 'SecureCode™', 'MASTERCARD©', 'Atos Worldline', 'https://ssl-qlf-u5g-fo-acs-ve.wlp-acs.com'),
  ('VISA', '05', '06', 'Verified by VISA™', 'VISA™', 'Atos Worldline', 'https://ssl-qlf-u5g-fo-acs-ve.wlp-acs.com');
/*!40000 ALTER TABLE `CARDNETWORK` ENABLE KEYS */;

DROP TABLE IF EXISTS `ISSUER_CONFIG`;
CREATE TABLE IF NOT EXISTS `ISSUER_CONFIG` (
  `SUB_ISSUER_NAME` varchar(255) NOT NULL,
  `ACS_ID` varchar(255) NOT NULL,
  `AUTHENTICATION_TIMEOUT` int(11) DEFAULT NULL,
  `AUTOMATIC_DEVICE_SELECTION` tinyint(1) NOT NULL,
  `BACKUP_ALLOWED` tinyint(1) NOT NULL,
  `BACKUP_LANGUAGES` varchar(255) NOT NULL,
  `CAVV_KEY_INDICATOR` varchar(255) NOT NULL,
  `DEFAULT_DEVICE_CHOICE` tinyint(1) NOT NULL,
  `DEFAULT_LANGUAGE` varchar(2) DEFAULT NULL,
  `FRESHNESS_PERIOD` int(11) DEFAULT NULL,
  `ISSUER_FULLNAME` varchar(255) DEFAULT NULL,
  `HUB_CALLMODE` varchar(255) DEFAULT NULL,
  `ISSUER_COUNTRY` varchar(255) NOT NULL,
  `ISSUER_CODE` varchar(255) DEFAULT NULL,
  `PREFERRED_AUTHENT_MEANS` varchar(255) DEFAULT NULL,
  `ISSUER_NAME` varchar(255) DEFAULT NULL,
  `SECOND_FACTOR_AUTHENTICATION` varchar(255) DEFAULT NULL,
  `SUB_ISSUER_CODE` varchar(255) NOT NULL,
  `SUB_ISSUER_FULLNAME` varchar(255) DEFAULT NULL,
  `TRANSACTION_TIMEOUT` int(11) DEFAULT NULL,
  `USER_CHOICE_ALLOWED` tinyint(1) NOT NULL,
  `RESET_BACKUPS` tinyint(1) DEFAULT NULL,
  `RESET_CHOICES` tinyint(1) DEFAULT NULL,
  `ADDITIONAL_INFO` text,
  `BACKUP_COMBINED_AMOUNT` tinyint(1) DEFAULT '0',
  `CHOICES_COMBINED_AMOUNT` tinyint(1) DEFAULT '0',
  `IVR_CODE` varchar(255) DEFAULT NULL,
  `OTP_ALLOWED_CHARS` varchar(255) DEFAULT NULL,
  `OTP_EXCLUDED_CHARS` varchar(255) DEFAULT NULL,
  `CIPHER_KEY_IDENTIFIER` varchar(255) NOT NULL,
  `ACS_ID_FOR_CRYPTO` varchar(2) NOT NULL,
  `BIN_KEY_IDENTIFIER` varchar(1) NOT NULL,
  `HUB_AES_KEY` varchar(45) NOT NULL,
  `DES_CIPHER_KEY_IDENTIFIER` varchar(255) NOT NULL,
  `DES_KEY_ID` varchar(45) NOT NULL,
  `RBA_THRESHOLD` int(11) NOT NULL,
  `MASK_PARAMS` varchar(50) DEFAULT NULL,
  `DATE_FORMAT` varchar(50) DEFAULT NULL,
  `TWO_STEP_CANCELLATION` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`SUB_ISSUER_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `MERCHANT_THRS_CONFIG`;
CREATE TABLE IF NOT EXISTS `MERCHANT_THRS_CONFIG` (
  `ID` bigint(20) NOT NULL,
  `LEVEL` varchar(255) DEFAULT NULL,
  `LEVEL_VALUE` varchar(45) DEFAULT NULL,
  `KEY_WORD` varchar(45) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `THRESHOLD_AMOUNT` bigint(20) DEFAULT NULL,
  `DISPLAY_NULL_AMOUNT` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PROFILE_SET`;
CREATE TABLE IF NOT EXISTS `PROFILE_SET` (
  `ID` varchar(16) NOT NULL,
  `PROFILE_SET` mediumtext,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `USER_CONFIG`;
CREATE TABLE IF NOT EXISTS `USER_CONFIG` (
  `TOKEN_PAN` varchar(32) NOT NULL,
  `USER_CONFIG_COUNTER` text,
  `PROFILE_SET_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TOKEN_PAN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
