/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

USE `U5G_ACS_BO`;

ALTER TABLE `CustomItem` ADD `fk_id_font` BIGINT(20) NULL AFTER `fk_id_image`;

CREATE TABLE IF NOT EXISTS `Font` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `createdBy` varchar(255) NOT NULL,
  `creationDate` datetime NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `mimeType` varchar(255) DEFAULT NULL,
  `lastUpdateBy` varchar(255) DEFAULT NULL,
  `lastUpdateDate` datetime DEFAULT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `updateState` varchar(255) NOT NULL,
  `binaryData` longblob,
  PRIMARY KEY (`id`,`name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;