USE PORTAL_SERVICE_PARAM;

-- check existing 
SET @serviceName = 'ACS_U5G' COLLATE utf8_unicode_ci;
SET @serviceNamePortail = 'PORTAIL' COLLATE utf8_unicode_ci;
SET @roleName = 'ADMIN_SPARDA' COLLATE utf8_unicode_ci; 

SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

-- insert any user by login to a specific role
SET @roleId = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
SET @serviceId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceName);
SET @servicePortailId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceNamePortail);

/* Christian Schnur */
SET @userLogin = 'EWLA790281' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Nicolas Pascal
SET @userLogin = 'A176981' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Aarti Priya
SET @userLogin = 'EWLA185629' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Dajana Eisenhauer
SET @userLogin = 'EWLdEisenhauer' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Tillmann Schmitt
SET @userLogin = 'A562490' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Nicolas Engel
SET @userLogin = 'A663859' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Tim Milde
SET @userLogin = 'A758569' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;


-- check existing 
SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

USE PORTAL_SERVICE_PARAM;

-- check existing 
SET @serviceName = 'ACS_U5G' COLLATE utf8_unicode_ci;
SET @serviceNamePortail = 'PORTAIL' COLLATE utf8_unicode_ci;
SET @roleName = 'AGENT_SPARDA' COLLATE utf8_unicode_ci; 

SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);


-- insert any user by login to a specific role
SET @roleId = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
SET @serviceId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceName);
SET @servicePortailId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceNamePortail);

/* Christian Schnur */
SET @userLogin = 'EWLA790281' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Nicolas Pascal
SET @userLogin = 'A176981' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Aarti Priya
SET @userLogin = 'EWLA185629' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Dajana Eisenhauer
SET @userLogin = 'EWLdEisenhauer' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Tillmann Schmitt
SET @userLogin = 'A562490' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Nicolas Engel
SET @userLogin = 'A663859' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Tim Milde
SET @userLogin = 'A758569' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- check existing 
SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

USE PORTAL_SERVICE_PARAM;

-- check existing 
SET @serviceName = 'ACS_U5G' COLLATE utf8_unicode_ci;
SET @serviceNamePortail = 'PORTAIL' COLLATE utf8_unicode_ci;
SET @roleName = 'SUPER_ADMIN_SPARDA' COLLATE utf8_unicode_ci; 

SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);

-- insert any user by login to a specific role
SET @roleId = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
SET @serviceId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceName);
SET @servicePortailId = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = @serviceNamePortail);

/* Christian Schnur */
SET @userLogin = 'EWLA790281' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Nicolas Pascal
SET @userLogin = 'A176981' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Aarti Priya
SET @userLogin = 'EWLA185629' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Dajana Eisenhauer
SET @userLogin = 'EWLdEisenhauer' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Tillmann Schmitt
SET @userLogin = 'A562490' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Nicolas Engel
SET @userLogin = 'A663859' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- Tim Milde
SET @userLogin = 'A758569' COLLATE utf8_unicode_ci;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@serviceId;
DELETE FROM PROFIL WHERE USER_XARM_LOGIN=@userLogin AND ROLE_ID=@roleId AND SERVICE_ID=@servicePortailId;

-- check existing 
SELECT * FROM PROFIL p 
WHERE p.SERVICE_ID = (SELECT SERVICE_ID FROM SERVICE WHERE SERVICE_NAME = 'ACS_U5G' LIMIT 1)
AND p.ROLE_ID IN 
(SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = @roleName);
