USE `U7G_ACS_BO`;

INSERT INTO `Association` (`groupPath`, `role`) VALUES
	('/All/76700', 'ADMIN'),
	('/All/76700', 'HELPDESK'),
	('/All/76700', 'REPORTING');

SELECT @adminId := id FROM Association WHERE groupPath = '/All/76700' AND role = 'ADMIN';
SELECT @helpdeskId := id FROM Association WHERE groupPath = '/All/76700' AND role = 'HELPDESK';
SELECT @reportingId := id FROM Association WHERE groupPath = '/All/76700' AND role = 'REPORTING';


INSERT INTO PermissionAssociation (associationId, permissionId)
SELECT @adminId, p.id FROM Permission p WHERE p.name IN ("PAN:READ","TRANSACTION:READ","REPORTING:READ","BIN:READ","BIN:WRITE","BIN_EXPORT:READ","CARD:READ","AUTH_MEANS:WRITE","STATIC_COUNTER:WRITE","FRAUD:READ","FRAUD:DELETE","CARD_BLACKLIST:WRITE",
"PROFILE:READ","PROFILE:WRITE","AUTH_MEANS:READ","ISSUER:READ","ISSUER:WRITE","INSTANCE:READ","INSTANCE:WRITE","HUB_DATA:READ","INTERNAL_DATA:READ","FO_SYNCHRONIZATION:WRITE","USER_XP:READ","MERCHANT_PIVOT:READ","MERCHANT_PIVOT:WRITE",
"AUDIT:READ","EXTERNAL_WS:READ","PROTOCOL_VERSION_2:READ","PROTOCOL_VERSION_102:READ","RBA_DECISION:READ","BLACKLISTED_AUTHENTICATION_MEANS:READ","BLACKLISTED_AUTHENTICATION_MEANS:WRITE","IP_FILTERS:READ","IP_FILTERS:WRITE",
"BLACKLISTED_MERCHANTS:READ","BLACKLISTED_MERCHANTS:WRITE","BLACKLISTED_COUNTRIES:READ","BLACKLISTED_COUNTRIES:WRITE","CARD_BLACKLIST:READ","CARD_WHITELIST:READ","CARD_WHITELIST:WRITE","INTERNAL_DATA:WRITE","CARD_PROFILESET_NAME:WRITE",
"CARD_PROFILESET_NAME:READ","CARD_EXEMPTION:READ","CARD_EXEMPTION:WRITE","BATCH_REPORTS:READ","RBA_CONFIGURATION:READ","PSD2_REPORTS:READ","BIN_EMERGENCY:WRITE","RBA_CONFIGURATION_DETAILS:READ","ENROLMENT:READ",
"RBA_CONFIGURATION_DETAILS:WRITE","ENROLMENT_REPORT:READ","Authent_DATA:WRITE","IMPORT_EXPORT_TOOL:IMPORT","AUDIT_CONFIGURATION:WRITE","AUDIT_CONFIGURATION:READ","TRUSTED_BENEFICIARIES:READ","CRYPTO_CONFIG:READ","AUTHENTICATION_HEX:READ",
"REPORT_PROFILESET:READ","REPORT_BIN_RANGE:READ","AUDIT_PCI:READ","SEARCH_CARD_FRAUD:READ","APM_COUNTER:READ","RBA_MERCHANT_CONFIGURATIONS:READ","RBA_MERCHANT_CONFIGURATIONS:WRITE");

INSERT INTO PermissionAssociation (associationId, permissionId)
SELECT @reportingId, p.id FROM Permission p WHERE p.name IN ("TRANSACTION:READ","REPORTING:READ","PROTOCOL_VERSION_2:READ","PROTOCOL_VERSION_102:READ");

INSERT INTO PermissionAssociation (associationId, permissionId)
SELECT @helpdeskId, p.id FROM Permission p WHERE p.name IN ("PAN:READ","TRANSACTION:READ","REPORTING:READ","BIN:READ","BIN_EXPORT:READ","CARD:READ","PROFILE:READ","USER_XP:READ","PROTOCOL_VERSION_2:READ","PROTOCOL_VERSION_102:READ","RBA_DECISION:READ",
"BATCH_REPORTS:READ","REPORT_PROFILESET:READ","REPORT_BIN_RANGE:READ");
