USE `U5G_ACS_FO`;

DELETE FROM `PROFILE_SET` WHERE  PROFILE_SET like '%PS_LBB_01%';

SET @CryptoConfigId_LBB = (SELECT CRYPTO_CONFIG_ID FROM ISSUER_CONFIG WHERE `ISSUER_NAME` = 'LANDESBANK_BERLIN'
                                                                        AND `ISSUER_CODE` = '19600');
DELETE FROM `CRYPTO_CONFIG` WHERE `ID` = @CryptoConfigId_LBB;

DELETE FROM `ISSUER_CONFIG` WHERE `ISSUER_NAME` = 'LANDESBANK_BERLIN'
                              AND `ISSUER_CODE` = '19600';

DELETE FROM `BIN_RANGE` WHERE SUB_ISSUER_CODE = '19600';
