/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

USE `U0M_ACS_MONITOR`;

/*!40000 ALTER TABLE `SERVICE_INFO` DISABLE KEYS */;
INSERT INTO `SERVICE_INFO` (`SERVICE_NAME`, `SITE_NAME`, `ACS_ID`, `ADDITIONAL_INFO`, `SCOPE`) VALUES
  ('authent.hub', 'Vendome', 'U5G', '{"machineInfo":{"tqacsk02v":{"additionalInfo":{"hub.jks.truststore.file":"SSLKeysRCT.jks","hub.p12.truststore.file":"test-acs.wlp-acs.com.p12","hub.temp.configuration.file":"hub-configs.properties","hub.proxy.host":"proxy-prod.priv.atos.fr","hub.proxy.port":"3128"},"serviceUrl":"https://ssl-qlf-uxa-fo-hub-cpr.ita.stg.as8677.net/u9f/proxy/rest","servicePort":null,"proxyHost":null,"proxyPort":null,"serverUrl":"https://ssl-qlf-uxa-fo-hub-cpr.ita.stg.as8677.net/u9f/proxy/rest","serviceStatus":"OK","serviceStatusInfo":null,"serviceDependencies":[],"version":"1.1.22-ICG"},"tqacsk01v":{"additionalInfo":{"hub.jks.truststore.file":"SSLKeysRCT.jks","hub.p12.truststore.file":"test-acs.wlp-acs.com.p12","hub.temp.configuration.file":"hub-configs.properties","hub.proxy.host":"proxy-prod.priv.atos.fr","hub.proxy.port":"3128"},"serviceUrl":"https://ssl-qlf-uxa-fo-hub-cpr.ita.stg.as8677.net/u9f/proxy/rest","servicePort":null,"proxyHost":null,"proxyPort":null,"serverUrl":"https://ssl-qlf-uxa-fo-hub-cpr.ita.stg.as8677.net/u9f/proxy/rest","serviceStatus":"OK","serviceStatusInfo":null,"serviceDependencies":[],"version":"1.1.22-ICG"}}}', 0),
  ('flash', 'Vendome', 'U5G', '{"machineInfo":{"tqacsk02v":{"additionalInfo":{"flash.server.url":"http://flash.ext.ita.rocks/flash","flash.proxy.host":"","flash.proxy.port":"","flash.connect.timeout":"300","flash.read.timeout":"300","flash.key.store.file":"/MIDDLE/u9f_wlpacs/u9f-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/test-acs.wlp-acs.com.p12","flash.key.store.type":"PKCS12","flash.key.store.password":"eXepbED4hIjdMrhysqkj","flash.initial.delay":"1000","flash.min.aleatory":"10","flash.max.aleatory":"100","flash.max.tryouts":"20","flash.coefficient":"2.0","flash.unsecure.mode":"true","flash.collection.id.pages":"acs-ux-rbu3-u9f","flash.collection.id.session":"acs-authentication-rbu3-u9f"},"serviceUrl":"http://flash.ext.ita.rocks/flash","servicePort":null,"proxyHost":"proxy-prod.priv.atos.fr","proxyPort":"3128","serverUrl":"http://flash.ext.ita.rocks/flash","serviceStatus":"OK","version":"2.5.1","serviceStatusInfo":null,"serviceDependencies":[]},"tqacsk01v":{"additionalInfo":{"flash.server.url":"http://flash.ext.ita.rocks/flash","flash.proxy.host":"","flash.proxy.port":"","flash.connect.timeout":"300","flash.read.timeout":"300","flash.key.store.file":"/MIDDLE/u9f_wlpacs/u9f-fo-acs-hzcmod/jboss/modules/acs3/com/worldline/acs/configuration/session/main/properties/test-acs.wlp-acs.com.p12","flash.key.store.type":"PKCS12","flash.key.store.password":"eXepbED4hIjdMrhysqkj","flash.initial.delay":"1000","flash.min.aleatory":"10","flash.max.aleatory":"100","flash.max.tryouts":"20","flash.coefficient":"2.0","flash.unsecure.mode":"true","flash.collection.id.pages":"acs-ux-rbu3-u9f","flash.collection.id.session":"acs-authentication-rbu3-u9f"},"serviceUrl":"http://flash.ext.ita.rocks/flash","servicePort":null,"proxyHost":"proxy-prod.priv.atos.fr","proxyPort":"3128","serverUrl":"http://flash.ext.ita.rocks/flash","serviceStatus":"OK","version":"2.5.1","serviceStatusInfo":null,"serviceDependencies":[]}}}', 0),
  ('hazelcast', 'Vendome', 'U5G', '{"machineInfo": {  "tqacsk01v": {    "additionalInfo": {      "hazelcast.client.reconnection.timeout": "5000",      "hazelcast.client.addresses": "10.72.38.52:8200;10.72.39.5:8200",      "hazelcast.client.shuffle.addresses": "false",      "hazelcast.client.group.pass": "dev-pass",      "hazelcast.client.reconnection.attempts.limit": "10",      "hazelcast.client.connection.timeout": "3000",      "hazelcast.client.update.automatic": "true",      "hazelcast.client.connection.attempts.limit": "3",      "hazelcast.client.group.name": "dev"    },    "serviceUrl": "http://10.72.38.52",    "serverUrl": "http://10.72.38.52",    "servicePort": null,    "proxyHost": null,    "proxyPort": null,    "serviceStatus": "OK",    "version": "2.5.1"  },  "tqacsk02v": {    "additionalInfo": {      "hazelcast.client.reconnection.timeout": "5000",      "hazelcast.client.addresses": "10.72.38.52:8200;10.72.39.5:8200",      "hazelcast.client.shuffle.addresses": "false",      "hazelcast.client.group.pass": "dev-pass",      "hazelcast.client.reconnection.attempts.limit": "10",      "hazelcast.client.connection.timeout": "3000",      "hazelcast.client.update.automatic": "true",      "hazelcast.client.connection.attempts.limit": "3",      "hazelcast.client.group.name": "dev"    },    "serviceUrl": "http://10.72.39.5",    "serverUrl": "http://10.72.39.5",    "servicePort": null,    "proxyHost": null,    "proxyPort": null,    "serviceStatus": "OK",    "version": "2.5.1"  }}}', 0);
/*!40000 ALTER TABLE `SERVICE_INFO` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;