USE U7G_ACS_BO;

UPDATE `Profile` SET `maxAttempts` = 3 WHERE `name` IN ('CS_ACCEPT',
														'CS_DECLINE',
														'NAB_ACCEPT',
														'NAB_DECLINE',
														'SGKB_ACCEPT',
														'SGKB_DECLINE',
														'SGKB_TA_01',
														'SGKB_SMS_01',
														'SOBA_ACCEPT',
														'SOBA_DECLINE',
														'LUKB_ACCEPT',
														'LUKB_DECLINE',
														'BEKB_ACCEPT',
														'BEKB_DECLINE',
														'GRKB_ACCEPT',
														'GRKB_DECLINE',
														'TGKB_ACCEPT',
														'TGKB_DECLINE',
														'LLB_ACCEPT',
														'LLB_DECLINE',
														'LLB_PASSWORD_01',
														'BALI_ACCEPT',
														'BALI_DECLINE');